CREATE TABLE EXAM (
    CLASS_NAME      VARCHAR2(255)
    , STUDENT_NAME  VARCHAR2(255)
    , SCORE         INT
    , GRADE         VARCHAR2(1)
)
;

INSERT INTO EXAM
(CLASS_NAME, STUDENT_NAME, SCORE) VALUES
('MATH'    , 'Fwantastic', 64   )
;

INSERT INTO EXAM
(CLASS_NAME, STUDENT_NAME, SCORE) VALUES
('MATH'    , 'IU'        , 95   )
;

INSERT INTO EXAM
(CLASS_NAME        , STUDENT_NAME, SCORE) VALUES
('COMPUTER SCIENCE', 'Fwantastic', 100  )
;

INSERT INTO EXAM
(CLASS_NAME        , STUDENT_NAME, SCORE) VALUES
('COMPUTER SCIENCE', 'IU'        , 86   )
;

INSERT INTO EXAM
(CLASS_NAME        , STUDENT_NAME, SCORE) VALUES
('COMPUTER SCIENCE', '수지'       , 77   )
;